### ISSUE TITLE
Give user one line information according to time

### ISSUE THREAD

**Issue by Volcano-Dragon** [Rakesh9100/Greeting-Time#1]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Im adding a new feature to print or show one line of useful information when someone opens up the application.
for example, if it is morning, then it will print one motivational quote for better start to the day
if it is afternoon, then it will print one facts for increasing the knowledge.
if it is eveing then it will some tricks and tips so you can make your life more convient.

Im creating this issue for SLOP 3.0

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @Volcano-Dragon Go ahead!!
