### ISSUE TITLE
Updating the readme file for new features

### ISSUE THREAD

**Issue by Volcano-Dragon** [Rakesh9100/Greeting-Time#10]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Updating the readme file for the new current temp feature

Adding new section for installing the required libraries and updating all other minor details

The basic structure of the Readme file will be maintained.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
PR status pls @Volcano-Dragon

**Comment by Volcano-Dragon** [comment]
> PR status pls @Volcano-Dragon

Created new pull request #11 for this issue
