### ISSUE TITLE
Updating Readme file for Quotes

### ISSUE THREAD

**Issue by Volcano-Dragon** [Rakesh9100/Greeting-Time#3]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Updating the readme file and adding how to contribute to adding quotes, what is the basic file structure that needs to be followed to make the **TEXT** files properly works? How the current program selects and prints the quotes.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Status of your PR @Volcano-Dragon

**Comment by Volcano-Dragon** [comment]
> Status of your PR @Volcano-Dragon

creating PR soon
