### ISSUE TITLE
Adding current temperature

### ISSUE THREAD

**Issue by Volcano-Dragon** [Rakesh9100/Greeting-Time#6]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

When ever user open the application the program will display the current temp. , humidity, wind speed in console.
User first need to add there location in one text file (only one time process) so program can read that file and fetch the current temp.

Notes: 

- Currently im using free account of API: so API request is limited to 1000 per month (ig it is fine for contribution period)

- User need to install this two library

```
#include <curl/curl.h>
#include <nlohmann/json.hpp>
```

### Screenshots

![image](https://github.com/Rakesh9100/Greeting-Time/assets/93902835/2ecb562b-09e8-4246-997d-afe239868724)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Seems good!!
Assigned @Volcano-Dragon, Proceed!
