### ISSUE TITLE
Adding GUI window for greeting

### ISSUE THREAD

**Issue by Volcano-Dragon** [Rakesh9100/Greeting-Time#7]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Converting the console application to the GUI-based window application

Notes:

- GUI window only works on MS Windows OS.
- #include <window.h> header file is required

### Screenshots

![image](https://github.com/Rakesh9100/Greeting-Time/assets/93902835/4a31edd8-b5de-45ff-9fa2-1bc089667397)

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Will assign after the completion of previous assigned issue @Volcano-Dragon
