### ISSUE TITLE
Bug fixes in code and readme file

### ISSUE THREAD

**Issue by Volcano-Dragon** [Rakesh9100/Greeting-Time#8]
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Fixing some typos in program and screenshot link issue in readme file

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/Greeting-Time/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

**Comment by Rakesh9100** [comment]
Assigned @Volcano-Dragon
